nsxiv-cb: remove some unneeded logs and use stderr
error messages should be sent to stderr.

and there's no need to have unnecessary messages that are not very
interesting and/or useful to the end-user:
http://www.linfo.org/rule_of_silence.html

diff --git a/patches/cb_mode/nsxiv-cb b/patches/cb_mode/nsxiv-cb
--- a/patches/cb_mode/nsxiv-cb
+++ b/patches/cb_mode/nsxiv-cb
@@ -2,7 +2,7 @@
 # Opens an archive in nsxiv.
 
 if [ "$1" = "" ]; then
-    echo "Usage: $0 <archive>"
+    echo "Usage: $0 <archive>" >&2
     exit 1
 fi
 
@@ -30,7 +30,6 @@ if [ -e "$NSXIV_SESSION_FILE" ]; then
     NSXIV_SESSION_FILE_INDEX="$(echo "$NSXIV_SESSION_FILE_CONTENTS" | cut -f1)"
 else
     NSXIV_SESSION_FILE_INDEX=1
-    echo "Session file not found. Starting from beginning."
 fi
 
 EXIT_OUTPUT="$(nsxiv -a -b -p -s w -q -r -C -n"$NSXIV_SESSION_FILE_INDEX" "$mnt")"
@@ -42,26 +41,21 @@ EXIT_FILE_NAME="$(basename "$EXIT_FILE_NAME")"
 
 if [ -n "$EXIT_FILE_NAME" ]; then
     if [ "$EXIT_FILE_INDEX" == "1" ]; then
-        echo "First page, not saving."
         if [ -e "$NSXIV_SESSION_FILE" ]; then
             rm "$NSXIV_SESSION_FILE"
         fi
         exit 0
     fi
     if [ "$EXIT_FILE_INDEX" == "$EXIT_FILE_COUNT" ]; then
-        echo "Last page, not saving. Deleting NSXIV_HIST_FILE."
         if [ -e "$NSXIV_SESSION_FILE" ]; then
             rm "$NSXIV_SESSION_FILE"
         fi
         exit 0
     fi
     if [ "$EXIT_FILE_INDEX" != "$NSXIV_SESSION_FILE_INDEX" ]; then
-        echo "Saving to '$NSXIV_SESSION_FILE'."
         printf '%s\t%s\t%s\t%s\t%s' "$EXIT_FILE_INDEX" "$EXIT_FILE_COUNT" "$EXIT_FILE_NAME" "$CB_FILE_BASE" "$CB_FILE_DIRNAME" >"$NSXIV_SESSION_FILE"
-    else
-        echo "Same index as in history file, not saving."
     fi
 else
-    echo "Unknown error, not saving."
+    echo "Unknown error, not saving." >&2
 fi
 
