nsxiv-pipe: simplify the script
remove trying to drain pipes from the argument list. this was
never really sound because it wouldn't work for multiple pipes
plus the script has no way of knowing which is a file argument
vs which are nsxiv flags (e.g --fullscreen).

diff --git a/scripts/nsxiv-pipe/nsxiv-pipe b/scripts/nsxiv-pipe/nsxiv-pipe
--- a/scripts/nsxiv-pipe/nsxiv-pipe
+++ b/scripts/nsxiv-pipe/nsxiv-pipe
@@ -1,24 +1,24 @@
 #!/bin/sh
 
 tmpfile="${TMPDIR:-/tmp}/nsxiv_pipe_$$"
-trap 'rm -f -- $tmpfile' EXIT TERM INT
+trap 'rm -f -- "$tmpfile"' EXIT TERM INT QUIT
 
-if [ "$#" -eq 0 ]; then
-    if [ -t 0 ]; then
-        echo "nsxiv-pipe: No arguments provided" >&2; exit 1
-    else
-        # Consume stdin and put it in the temporal file
-        cat > "$tmpfile"
-    fi
+if ! [ -t 0 ]; then
+    # drain stdin to tmpfile if it's not connected to a terminal
+    cat > "$tmpfile" || { echo "draining stdin failed" >&2; exit 1; }
 fi
 
-for arg in "$@"; do
-    # if it's a pipe then drain it to $tmpfile
-    [ -p "$arg" ] && cat "$arg" > "$tmpfile"
-done
-
 if [ -s "$tmpfile" ]; then
-    nsxiv -q "$@" "$tmpfile" # -q to silence warnings
-else
-    nsxiv "$@" # fallback
+    nsxiv "$tmpfile" "$@"
+else  # fallback
+    [ "$#" -eq 0 ] && {
+        cat >&2 << EOF
+nsxiv-pipe: Error: no file or stdin provided
+Usage:
+  nsxiv-pipe < /path/to/file
+  curl "\$image_url" | nsxiv-pipe
+EOF
+        exit 1;
+    }
+    nsxiv "$@"
 fi
